created user model and its test cases
oyasr/TheInkSpot pull request #23
Opened 2022-05-01 16:09 UTC by MahmoudSaeed13

- Created the user model.
- Written the test cases to test all the parameters of every property of the user object.

2022-05-06 16:08 UTC, ahmedeltaweel requested changes
LGTM! some comments to consider, please check them.

2022-05-06 16:08 UTC, ahmedeltaweel commented on makefile
> +	docker-compose -f local.yml exec -e DJANGO_SETTINGS_MODULE=config.settings.test django /entrypoint python manage.py test $(filter-out $@,$(MAKECMDGOALS))
Take care of pytest as it's not like unittest.
and validate that we can send custom parameters

2022-05-06 16:08 UTC, ahmedeltaweel commented on theinkspot/users/admin.py
> +    add_fieldsets = (
Would you please attach screenshot ?

2022-05-06 16:08 UTC, ahmedeltaweel commented on theinkspot/users/forms.py
> +from django import forms
feel free to remove the forms file and its logic.As we will not use it we will rely on APIs

2022-05-06 16:08 UTC, ahmedeltaweel commented on theinkspot/users/migrations/0001_initial.py
> +# Generated by Django 3.2.12 on 2022-05-01 11:42
Please squash to only 1 migration per PR.

2022-05-06 16:08 UTC, ahmedeltaweel commented on theinkspot/users/models.py
> +        if username is None:
```suggestion
        if username:
```

2022-05-06 18:14 UTC, MahmoudSaeed13 commented on theinkspot/users/admin.py
> +    add_fieldsets = (
![Screenshot from 2022-05-06 20-10-32](https://user-images.githubusercontent.com/89417047/167194741-c194ec78-82f5-4895-a0a7-890cf5e946e7.png)
![Screenshot from 2022-05-06 20-10-19](https://user-images.githubusercontent.com/89417047/167194847-59b1bc29-3b97-4c0f-8a65-ee520590cbfa.png)

we added the field (is user verified by email) to the user view page & add two fields(name & email) to the add user form

2022-05-06 18:17 UTC, MahmoudSaeed13 commented on theinkspot/users/forms.py
> +from django import forms
we will not be working with forms, we needed this only for the admin panel.

2022-05-07 23:14 UTC, ahmedeltaweel approved these changes
LGTM! only comment is to remove vscode config from code repo.
add .vscode to .gitignore

2022-05-08 12:32 UTC, merged