Ink 2 registration and login system
oyasr/TheInkSpot pull request #73
Opened 2022-07-25 23:06 UTC by shroukhegazi

- Created a User Registration system.
- Created User Login System.
- Sent Verification Mail.
- Write Test Cases to Test all Views.

2022-07-26 19:53 UTC, MoazSamy approved these changes
LGTM, I just think it'd be better to separate authentication urls/tests in a separate app 😄

2022-07-28 19:21 UTC, ahmedeltaweel requested changes

2022-07-28 19:21 UTC, ahmedeltaweel commented on config/settings/base.py
> +# EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
this should have no effect on the current PR. please revert

2022-07-28 19:21 UTC, ahmedeltaweel commented on config/settings/base.py
> +EMAIL_HOST = "localhost"
this exists in local.py. please remove.

2022-07-28 19:21 UTC, ahmedeltaweel commented on config/urls.py
>      path("users/", include("theinkspot.users.urls", namespace="users")),
remove views. we only work with apis

2022-07-28 19:21 UTC, ahmedeltaweel commented on requirements/base.txt
> +pytest-mock==3.8.2
base is only for common packages

2022-07-28 19:21 UTC, ahmedeltaweel commented on theinkspot/users/api/helpers.py
> +    if not (re.fullmatch(r"[A-Za-z0-9@#$%^&+=]{8,}", password)):
```suggestion
    return not (re.fullmatch(r"[A-Za-z0-9@#$%^&+=]{8,}", password))
```

2022-07-28 19:21 UTC, ahmedeltaweel commented on theinkspot/users/api/serializers.py
> +        fields = "__all__"
Please be explicit as possible

2022-07-28 19:21 UTC, ahmedeltaweel commented on theinkspot/users/api/serializers.py
> +        fields = "__all__"
one serializer for user is enough as model serializer

2022-07-28 19:21 UTC, ahmedeltaweel commented on theinkspot/users/api/urls.py
> +    path("register/", RegisterUsers.as_view(), name="register"),
you can consider Router

2022-07-28 19:21 UTC, ahmedeltaweel commented on theinkspot/users/api/views.py
> +# from email.message import _PayloadType
commented imports should be removed

2022-07-28 19:21 UTC, ahmedeltaweel commented on theinkspot/users/tests/test_views.py
> +from rest_framework.test import APIClient
revert here

2022-08-06 20:12 UTC, ahmedeltaweel approved these changes

2022-08-06 20:57 UTC, merged